SUSPICIOUS_PHRASES = {
    "urgent": 15,
    "verify your account": 20,
    "click here": 15,
    "suspended": 15,
    "dear customer": 10,
    "act now": 15,
    "24 hours": 10,
    "confirm your password": 20,
    "limited time": 10,
    "your account will be": 15,
    "winner": 10,
    "congratulations": 10,
    "bank account": 15,
    "social security": 20,
    "update your information": 15,
    "unusual activity": 15,
    "login immediately": 15,
    "claim your prize": 15,
}